[package]
name = "tano-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
tano-database = { path = "../tano-database" }
tano-macro = { path = "../tano-macro" }
color-eyre = "0.6.5"
tokio = { version = "1.49.0", features = ["full"] }
ratatui = "0.30.0"
