[package]
name = "tano-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
tokio = { version = "1.49.0", features = ["full"] }
tokio-stream = "0.1.18"
