[package]
name = "tano-database"
version = "0.1.0"
edition = "2024"

[dependencies]
tano-shared = { path = "../tano-shared" }
color-eyre = "0.6.5"
tokio = { version = "1.49.0", features = ["full"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
